package-lock.json
package.json
styles/style.css

https://github.com/keen/dashboard-builder/issues/28

Update theme builder css

---

styles/style.css

* https://github.com/keen/dashboard-builder/issues/56
* https://github.com/keen/dashboard-builder/issues/55
* styles for Edit button aligned with other btns

Scrolling content

---

lib/builder/components/EditorToolbar.js
lib/builder/components/SettingsChart.js
styles/style.css

metric chart added

---

lib/builder/components/Editor.js
lib/func/oldDashboardDataParse.js

Improvement of oldDashboardDataParser:
- fixing row titles duplications,
- fixing order of elements for mobile and tablet view(Viewer)
Fix for clearing dashboard while clicking on burger menu, when changes not saved

oldDashboardDataParser improvement and fix for Editor

---

lib/actions/rootActions.js
lib/builder/index.js
lib/index.js
lib/viewer/index.js
test/demo/index.html
webpack.config.js

it allows to connect to keen-web from localhost:8080 (local development)
important change is that we'll read projectId, masterKey etc from file `../demo-config.js` just like in other sdks

local dev cors

---

lib/func/checkBoundaries.js
lib/func/resizingCount.js

fix for moving and resizing charts while page scrolled down

---

lib/index.js
lib/viewer/components/EditorDashboard.js
lib/viewer/components/ExplorerButton.js
lib/viewer/index.js
styles/style.css

link to explorer to edit saved querys assigned to the charts

---

lib/builder/components/SettingsDashboard.js
package.json
styles/style.css

css tooltip fix and npm command improvement

---

styles/style.css

https://github.com/keen/dashboard-builder/issues/106

place text in dashboard menu vertically

---

lib/reducers/rootReducer.js
lib/viewer/components/MainListItemButtons.js

https://github.com/keen/dashboard-builder/issues/111

prevent dashboard removal once cancel is clicked

---

lib/viewer/components/MainListItem.js

https://github.com/keen/dashboard-builder/issues/110

go to viewer

---

lib/builder/components/EditorDashboardTopBar.js
lib/viewer/components/EditorContainer.js
lib/viewer/components/EditorTopToolbar.js
lib/viewer/components/EditorTopToolbarTitle.js
styles/style.css

https://github.com/keen/dashboard-builder/issues/112

edit button moved

---

lib/builder/components/Editor.js
lib/builder/components/EditorDashboardTopBar.js
lib/builder/components/EditorDashboardsSwitch.js
lib/builder/components/ShareDashboard.js

https://github.com/keen/dashboard-builder/issues/105

autoselect view mode

---

lib/actions/actionTypes.js
lib/actions/rootActions.js
lib/builder/components/Chart.js
lib/builder/components/ChartContainer.js
lib/builder/components/SettingsChart.js
lib/func/calculateCollisions.js
lib/reducers/rootReducer.js
lib/viewer/components/EditorDashboard.js
styles/style.css

#113
#96
Small fixes and prevent infinity loop for collisions

Dlacheta custom label

---

lib/builder/components/SettingsDashboard.js
lib/builder/components/ShareDashboard.js
lib/index.js
styles/style.css

https://github.com/keen/dashboard-builder/issues/130

help text added

---

lib/builder/components/EditorDashboardTopBar.js
lib/index.js
package.json
styles/style.css

https://github.com/keen/dashboard-builder/issues/14

export dashboard to png added

---

lib/builder/components/Accordion.js
lib/builder/components/SettingsDashboard.js
lib/builder/components/Switcher.js
lib/index.js
styles/style.css

to enable accordion
```
import Accordion from './Accordion';
...
<Accordion>
<div label="Accordion One">
<p>Lorem ipusm ...</p>
</div>
<div label="Accordion Two">
<p>Lorem ipsum ...</p>
</div>
<div label="Accordion Three">
<p>Lorem ipsum ...</p>
</div>
<div label="Accordion Four">
<p>Lorem ipsum ...</p>
</div>
<div label="Accordion Five">
<p>Lorem ipsum ...</p>
</div>
</Accordion>
```

accordion and switcher added

---

README.md
package-lock.json
package.json

Installed git-cz and commitizen
Closes: #219

chore: 🤖 initegration with git-cz

---

lib/actions/rootActions.js
lib/reducers/rootReducer.js
lib/utils/loadFontsFromDashboard.js
lib/utils/loadFontsFromDashboard.test.js
package.json

before the fix you need to trigger Theme Builder to load fonts from
Google
BREAKING CHANGE: n
Closes: #227

fix: 🐛 load fonts in viewer

---

styles/style.css

https://github.com/keen/theme-builder/issues/43

fix: 🐛 update position of color picker in right column

---

styles/style.css

fix: 🐛 set paddings for title/subtitle

---

lib/viewer/components/EditorDashboard.js

fix: 🐛 classic dashboard data parsing fix

---

lib/actions/rootActions.js
lib/reducers/rootReducer.js

https://github.com/keen/keen/issues/59

fix: 🐛 remove duplicate of delete chart confirmation

---

styles/style.css

https://github.com/keen/keen/issues/64

fix: 🐛 reset container height for dashboard list

---

styles/style.css

https://github.com/keen/keen/issues/62

enable scroll in viewer

---

styles/style.css

https://github.com/keen/keen/issues/63

fix: 🐛 enable scrolling on tables

---

lib/builder/components/Buttons.js
lib/builder/components/Chart.js
lib/builder/components/ChartContainer.js
lib/builder/components/Editor.js
lib/builder/components/EditorDashboardsSwitch.js
lib/builder/components/EditorToolbar.js
lib/builder/components/EmbedDashboard.js
lib/builder/components/Main.js
lib/builder/components/NewDashboardButton.js
lib/builder/components/SettingsChart.js
lib/builder/components/SettingsDashboard.js
lib/builder/components/SettingsImage.js
lib/builder/components/ShareDashboard.js
lib/builder/components/TextEditor.js
lib/reducers/rootReducer.js
lib/viewer/components/Editor.js
lib/viewer/components/EditorContainer.js
lib/viewer/components/EditorDashboard.js
lib/viewer/components/Main.js
lib/viewer/components/MainContainer.js
lib/viewer/components/MainListItemButtons.js
lib/viewer/components/MainTopToolbar.js
lib/viewer/components/SwitchDashboard.js

https://github.com/keen/keen/issues/91

refactor: 💡 draggedType should be string

---

lib/builder/components/Buttons.js
lib/builder/components/Chart.js
lib/builder/components/ChartContainer.js
lib/builder/components/Editor.js
lib/builder/components/EditorDashboardsSwitch.js
lib/builder/components/EditorToolbar.js
lib/builder/components/EmbedDashboard.js
lib/builder/components/Main.js
lib/builder/components/NewDashboardButton.js
lib/builder/components/SettingsChart.js
lib/builder/components/SettingsDashboard.js
lib/builder/components/SettingsImage.js
lib/builder/components/ShareDashboard.js
lib/builder/components/TextEditor.js
lib/viewer/components/Editor.js
lib/viewer/components/EditorContainer.js
lib/viewer/components/EditorDashboard.js
lib/viewer/components/Main.js
lib/viewer/components/MainContainer.js
lib/viewer/components/MainListItemButtons.js
lib/viewer/components/MainTopToolbar.js
lib/viewer/components/SwitchDashboard.js
package-lock.json

https://metakeen.atlassian.net/browse/FRON-8

fix: 🐛 time precision bug

---

lib/builder/components/Buttons.js
lib/builder/components/Chart.js
lib/builder/components/ChartContainer.js
lib/builder/components/Editor.js
lib/builder/components/EditorDashboardsSwitch.js
lib/builder/components/EditorToolbar.js
lib/builder/components/EmbedDashboard.js
lib/builder/components/Main.js
lib/builder/components/NewDashboardButton.js
lib/builder/components/SettingsChart.js
lib/builder/components/SettingsDashboard.js
lib/builder/components/SettingsImage.js
lib/builder/components/ShareDashboard.js
lib/builder/components/TextEditor.js
lib/viewer/components/Editor.js
lib/viewer/components/EditorContainer.js
lib/viewer/components/EditorDashboard.js
lib/viewer/components/Main.js
lib/viewer/components/MainContainer.js
lib/viewer/components/MainListItemButtons.js
lib/viewer/components/MainTopToolbar.js
lib/viewer/components/SwitchDashboard.js

https://metakeen.atlassian.net/browse/FEE-107

fix: 🐛 support stepLabels for funnel

---

lib/builder/components/EmbedDashboard.js

https://metakeen.atlassian.net/browse/FEE-596

fix: 🐛 add font alternative

---

lib/builder/components/Main.js
lib/index.js
lib/viewer/components/Editor.js
lib/viewer/components/EditorContainer.js
lib/viewer/components/EditorTopToolbar.js
lib/viewer/components/EditorTopToolbarTitle.js
lib/viewer/components/MainContainer.js
lib/viewer/components/MainTopToolbar.js

https://metakeen.atlassian.net/browse/FEE-643

feat: 🎸 hide buttons for transition mode
